name: Daily Crawl and Commit

on:
  schedule:
    - cron: "0 20 * * *"   # 每天 UTC 时间 20:00 执行（北京时间 4:00）
  workflow_dispatch:

permissions:
  contents: write

env:
  CRAWL_URL: "https://iot.mi.com/vela/quickapp/zh/"
  DOMAIN_DIR: "vele-docs"

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y wget pandoc
          export LANG=zh_CN.UTF-8
          export LC_ALL=zh_CN.UTF-8

      - name: Run wget mirror
        run: |
          wget --mirror \
               --convert-links \
               --adjust-extension \
               --page-requisites \
               --no-parent \
               --recursive \
               --level=6 \
               --domains=${DOMAIN_DIR} \
               --iri \
               --local-encoding=UTF-8 \
               --remote-encoding=UTF-8 \
               --no-if-modified-since \
               "${CRAWL_URL}" || true

      - name: Show wget log
        run: |
          echo "==== WGET LOG START ===="
          tail -n 50 wget.log || true
          echo "==== WGET LOG END ===="

      - name: Clean old markdown
        run: |
          echo "Cleaning old markdown files..."
          rm -rf ${DOMAIN_DIR}/markdown
          mkdir -p ${DOMAIN_DIR}/markdown

      - name: Convert HTML to Markdown
        run: |
          find ${DOMAIN_DIR} -type f -name "*.html" | while read file; do
            rel="${file#${DOMAIN_DIR}/}"
            target="${DOMAIN_DIR}/markdown/${rel%.html}.md"
            mkdir -p "$(dirname "$target")"
            pandoc "$file" -f html -t markdown -o "$target"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ${DOMAIN_DIR}
          git commit -m "chore: daily crawl & convert $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
